### PR TITLE
feat(beta): Updated to the latest beta and merged updates from main.

### PR DESCRIPTION
**Pull request by dlabaj**
This PR updates to the latest beta version and brings over all the updates that have happened in the main branch.

PR Preview can be found here:   https://questionable-celery.surge.sh

### CODE REVIEW

**Review by nicolethoen — APPROVED** [review]
Please create an issue to track removing the usage of the deprecated modal in the future.

Also, I think there should be an issue to track this comment left in a previous PR by @andrew-ronaldson. I noticed the issue still isn't resolved in your surge preview:
https://github.com/patternfly/react-user-feedback/pull/73#issuecomment-2191505448

**Review by edonehoo — APPROVED** [review]

**Review by wise-king-sullyman — APPROVED** [review]

**Comment by andrew-ronaldson** [comment]
I still see this padding issue with the background-image. Looks like a bug right now so I think the we need a a way to offset the padding back to the edge of the modal.
Screenshot 2024-08-06 at 12 43 22 PM

**Comment by dlabaj** [comment]
Screenshot 2024-08-07 at 2 58 39 PM

@andrew-ronaldson   All set andrew

**Review by andrew-ronaldson — APPROVED** [review]
Thanks for updating. Ship it!

**Pull request merged**
